In [9]:
import pandas as pd
df = pd.read_csv('../../data/restaurant/restaurant_truth2.csv',
                names=['name', 'BUILDING', 'STREET', 'ZIPCODE', 'PHONE', 'ID'])

In [10]:
row_num = df.shape[0]

In [17]:
def cmp(x, y):
    if  x > y:
        return 1
    elif x < y:
        return -1
    else:
        return 0

In [25]:
for i in range(row_num):
    print('-'*30,i,df.iloc[i].values.tolist())
    for j in range(row_num):
        if i== j:
            continue
        my_list = [cmp(df.iloc[i][n],df.iloc[j][n]) for n in range(5)]
        print(my_list)

------------------------------ 0 [8, 7, 0, 0, 10, 32]
[1, 1, 0, 0, 1]
[-1, -1, 0, -1, -1]
[-1, -1, -1, -1, -1]
[-1, -1, -1, -1, -1]
[-1, -1, -1, -1, -1]
[-1, -1, -1, -1, -1]
[-1, -1, -1, -1, -1]
[-1, -1, -1, -1, -1]
[-1, -1, -1, -1, -1]
------------------------------ 1 [2, 2, 0, 0, 2, 12]
[-1, -1, 0, 0, -1]
[-1, -1, 0, -1, -1]
[-1, -1, -1, -1, -1]
[-1, -1, -1, -1, -1]
[-1, -1, -1, -1, -1]
[-1, -1, -1, -1, -1]
[-1, -1, -1, -1, -1]
[-1, -1, -1, -1, -1]
[-1, -1, -1, -1, -1]
------------------------------ 2 [197, 155, 0, 8, 220, 313]
[1, 1, 0, 1, 1]
[1, 1, 0, 1, 1]
[-1, -1, -1, 1, -1]
[-1, -1, -1, 1, -1]
[-1, 1, -1, -1, -1]
[-1, -1, -1, -1, -1]
[-1, -1, -1, -1, -1]
[-1, -1, -1, -1, -1]
[-1, -1, -1, 1, -1]
------------------------------ 3 [1247, 805, 5, 7, 1392, 1830]
[1, 1, 1, 1, 1]
[1, 1, 1, 1, 1]
[1, 1, 1, -1, 1]
[-1, 1, -1, 1, -1]
[-1, 1, -1, -1, -1]
[-1, 1, -1, -1, -1]
[-1, 1, -1, -1, -1]
[1, 1, -1, -1, -1]
[1, 1, -1, 1, -1]
------------------------------ 4 [1499, 436, 7, 6, 1691, 2270]
[1, 1, 1, 1, 1]
[1, 1, 1, 1, 1]
[1, 1, 1, -1, 1]
[1, -1, 1, -1, 1]
[-1, 1, -1, -1, -1]
[-1, -1, -1, -1, -1]
[-1, -1, -1, -1, -1]
[1, 1, -1, -1, -1]
[1, -1, -1, 1, -1]
------------------------------ 5 [1717, 81, 9, 38, 1983, 2752]
[1, 1, 1, 1, 1]
[1, 1, 1, 1, 1]
[1, -1, 1, 1, 1]
[1, -1, 1, 1, 1]
[1, -1, 1, 1, 1]
[-1, -1, -1, 1, -1]
[-1, -1, -1, 1, -1]
[1, -1, -1, 1, -1]
[1, -1, -1, 1, -1]
------------------------------ 6 [1889, 451, 11, 19, 2195, 3081]
[1, 1, 1, 1, 1]
[1, 1, 1, 1, 1]
[1, 1, 1, 1, 1]
[1, -1, 1, 1, 1]
[1, 1, 1, 1, 1]
[1, 1, 1, -1, 1]
[-1, 0, 0, 0, -1]
[1, 1, -1, -1, -1]
[1, -1, -1, 1, -1]
------------------------------ 7 [1892, 451, 11, 19, 2200, 3090]
[1, 1, 1, 1, 1]
[1, 1, 1, 1, 1]
[1, 1, 1, 1, 1]
[1, -1, 1, 1, 1]
[1, 1, 1, 1, 1]
[1, 1, 1, -1, 1]
[1, 0, 0, 0, 1]
[1, 1, -1, -1, -1]
[1, -1, -1, 1, -1]
------------------------------ 8 [1026, 283, 19, 35, 10410, 3771]
[1, 1, 1, 1, 1]
[1, 1, 1, 1, 1]
[1, 1, 1, 1, 1]
[-1, -1, 1, 1, 1]
[-1, -1, 1, 1, 1]
[-1, 1, 1, -1, 1]
[-1, -1, 1, 1, 1]
[-1, -1, 1, 1, 1]
[1, -1, -1, 1, 1]
------------------------------ 9 [199, 796, 51, 2, 3527, 5107]
[1, 1, 1, 1, 1]
[1, 1, 1, 1, 1]
[1, 1, 1, -1, 1]
[-1, -1, 1, -1, 1]
[-1, 1, 1, -1, 1]
[-1, 1, 1, -1, 1]
[-1, 1, 1, -1, 1]
[-1, 1, 1, -1, 1]
[-1, 1, 1, -1, -1]